### ISSUE TITLE
Use SQL Store for Aries Framework

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/adapter#42]
Currently, leveldb is used as the backing storage for aries-framework-go. Update it to use SQL store, once its available in aries.

**Comment by llorllale** [comment]
being fixed in #216

**Comment by rolsonquadras** [comment]
This has been implemented now - https://github.com/trustbloc/adapter/blob/837ffabdd8ed11224679e6091083ace5460900c5/cmd/adapter-rest/startcmd/start.go#L265
