### ISSUE TITLE
Update To Latest Aries - including present proof & issue credential request refactoring

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/adapter#559]
pulling: 

- https://github.com/hyperledger/aries-framework-go/pull/3070
- https://github.com/hyperledger/aries-framework-go/pull/3091

**Comment by sudeshrshetty** [comment]
Blocking : https://github.com/trustbloc/adapter/issues/545

**Comment by rolsonquadras** [comment]
This has been implemented
