### ISSUE TITLE
[WACI-Issuance] Support to pass credential manifest

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/adapter#561]
As an Issuer, I should have the ability to configure the credential manifest in issuer-adapter. This manifest will be passed to Wallet as part of waci-issuance flow.

Crux of the discussion : 
How to configure the issuer 's credential manifest :  

1. To pass it as configurable  json file.
2. To have it accessible through the url most likely profile url available in the adaptor.

_**we will do step 1  for the initial iteraction .**_
Note that one Credential Manifest can support multiple types of credentials by using a different Output Descriptor for each credential. 

Instead of giving the user a giant Credential Manifest object with potentially many output descriptors that aren't of interest to the holder, the issuer/adapter can cut out the output descriptors that aren't relevant (or perhaps only add the output descriptors that are relevant).

**How does the issuer know which credential type the holder is going to ask for?**
We have something called credential scope for each transaction - based on scope issuer adapter can find out what it is going to issue. **Credential scope** is something we use in adapters, nothing to do with WACI.
in Aries bdd test the isssuer issues one type of credential for testing the flow. in Adapter, an issuer can issue multiple type of credentials

The json file key-value
[CredentialScope -> Array of OutputDescriptor], if in future if we have to issue multiple credential at once, it should work.

- [ ] #572 
- [ ] #579 
- [ ] #580 
- [ ] #581

**Comment by talwinder50** [comment]
Closed by mistake
