### ISSUE TITLE
Persist the manifest output descriptor in  local file based or in memory cache

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/adapter#579]
Since it is passed everytime you start adapter, it should be in some kind of local file. based or in-memory cache.

https://github.com/trustbloc/adapter/pull/574/files#diff-df62cee2a182a885095fde997637fe846f0b95210d33652c59d298ff2f395f28R895

**Comment by rolsonquadras** [comment]
This is a duplicate of https://github.com/trustbloc/adapter/issues/580
