### ISSUE TITLE
Create helper function for credential manifest output descriptors

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/adapter#580]
this object will be heavy, I would suggest you put a helper struct here which has functions to find and return subset of output descriptors by credential scope. So that you can swap underlying memory store with cache in future with little effort.

_Originally posted by @sudeshrshetty in https://github.com/trustbloc/adapter/pull/574#r791100399_

**Comment by talwinder50** [comment]
[&txnData ](https://github.com/trustbloc/adapter/blob/de984effb39b4eceea173db030558511b704f4cb/pkg/restapi/issuer/operation/operations.go#L1061)

When we are persisting transaction data with the cred=scope parameter  Issuer ID is profile id here.  Since profile data object also have new type named as Issuer Id  ` Issuer ID identifies who is the issuer of the credential manifests being issued.`  So it was sounding bit confusing to me.  Thats why i was thinking to rename IssuerID inside transaction to Profile ID.  

But i do see its also being used for mapping between inviationID and issuer.

**Comment by sudeshrshetty** [comment]
Rename it to IssuerProfileID to avoid confusion.
