### ISSUE TITLE
Refactor bdd test input parameters to struct 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/adapter#593]
With how many arguments are in this function, it makes sense to create a custom struct type to hold them all instead. This will also help to resolve the `lll` linter complaint.

_Originally posted by @DRK3 in https://github.com/trustbloc/adapter/pull/586#discussion_r793960952_

**Comment by rolsonquadras** [comment]
Since the params are called from feat file, this can't be changed - @sudeshrshetty @talwinder50 .

Closing the issue.
