### ISSUE TITLE
Support for submission requirement for WACI 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/adapter#612]
This is the advanced use case , Submission Requirement for waci is required. 

Use case scenario: Issue Driving license 
Requirement: Provide address proof 
Acceptable IDs:  Provide any two piece of IDs in order to validate the address, Permanent Resident Card, T4slip , Health Card. 
 Advanced use case put in backlog.

**Comment by rolsonquadras** [comment]
Add presentation_def parallel to output_descriptors in config - https://identity.foundation/credential-manifest/#credential-manifest---all-features-exercised
